# Generated by Django 5.0.4 on 2024-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
