# Generated by Django 5.0.4 on 2024-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
