# Generated by Django 5.0.4 on 2024-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_employee_confirm_password_employee_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
