# Generated by Django 5.0.4 on 2024-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_remove_employee_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
