# Generated by Django 5.0.4 on 2024-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0010_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
